import random

def guessthenumber(x):

    print("==========")
    print("Welcome my friendo!")
    print("==========")
    print("Your goal is to guess the number generated by the computer.")

    rnumber = random.randint(1, x) # Random number between 1 and x

    predict = 0 
    
    while predict != rnumber:
        # The user enters a number
        predict = int(input(f"Guess the number between 1 and {x}: ")) #f-string
        if predict < rnumber:
         print("try again, this number si too small.")
        elif predict > rnumber:
         print("try again, this number si too big.")
    

    print(f"Congrats! You guess the number {rnumber} correctly.")


guessthenumber(10)